language: go
go:
        - "1.10"
install:
        - go get -v github.com/Masterminds/glide
        - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.13.1 && go install && cd -
        - glide install
script:
        - go build -v
notifications:
        slack:
                secure: cTOI+LhlmQ0D46+CXVBozca0rSGSgBbMT3V/BEg5s1n0TsatRF8kQfPraBhIGBoZeGxALoDIA740VRxUUJ1e35fzncLe6RNsStMO/Nu1WhV5NwuPG03/od4yF8KEzuFWdBiXQgJDQ8fwNEem18B0H8+LDCMzPc0dJKnCmUfvx3Dpx0h7HdubnyC5yhTAjgu2YCnvYS+Q6RyGz6xruupONdN8zmGWeLVes3weKSksO3bKDUjdExtePM3nO4G/3PwQpJg5Os+iz22SO7Ufu+wBU7xMIWPHk7B6K5ipBZ7nF23kQvJvnqfFnFZ1qWYUHDCeo52qRLReMCaQnzoqkIe8GhpZgDr4cwx9tDDYRjl6ns0TbJ8AlNU8kmzBzKJoziXUF4wVzUly/txdloavcqnKNnSWKEfEx18/1tw1K7elzJ6wChTE6QySmm07rmVFEidK7KuVaZI6rSWu8Y4gtXWntty5FQc16DHCQz5DtyMGnKkerWdu95fjChcvDKcVmFcNB5WQM9BNAj8aRkJ+GxmA3pVtX/teehY9xszGN3dLw8Y0caVQ0NJeFUBLbAmGIDn05XPm4O3A0V++meV7dV6bFiXKvceKzhim6+qVvKk+t2EcwxbNv38tf7KFSNgDpmN8663H+AJ60kP+nEpmHI+uJAn/lpSYyOGYYJc4S6VH2PM=
