version: 2

jobs:

  build:
    working_directory: /go/src/github.com/FactomProject/factom-walletd
    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-factom-walletd-go-build-cache-{{ checksum "glide.lock" }}

      - run:
          name: Get glide
          command: |
            go get -v github.com/Masterminds/glide
            cd $GOPATH/src/github.com/Masterminds/glide
            git checkout tags/v0.13.1
            go install

      - run:
          name: Get goveralls
          command: |
            go get github.com/mattn/goveralls
            cd $GOPATH/src/github.com/Masterminds/glide
            git checkout tags/v0.13.1
            go install

      - run:
          name: Get the dependencies
          command: |
            glide install

      - run:
          name: Build and install the executable
          command: go install -v

      - save_cache:
          key: v1-factom-walletd-go-build-cache-{{ checksum "glide.lock" }}
          paths:
            - vendor

  test:
    working_directory: /go/src/github.com/FactomProject/factom-walletd
    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-factom-walletd-go-build-cache-{{ checksum "glide.lock" }}

      - run:
          name: Get glide
          command: |
            go get -v github.com/Masterminds/glide
            cd $GOPATH/src/github.com/Masterminds/glide
            git checkout tags/v0.13.1
            go install

      - run:
          name: Get goveralls
          command: |
            go get github.com/mattn/goveralls
            cd $GOPATH/src/github.com/Masterminds/glide
            git checkout tags/v0.13.1
            go install

      - run:
          name: Get the dependencies
          command: |
            glide install

      - run:
          name: Build and install the executable
          command: go install -v

      - run:
          name: Run tests!
          command: go test -v -vet=off $(glide nv)


      - save_cache:
          key: v1-factom-walletd-go-build-cache-{{ checksum "glide.lock" }}
          paths:
            - vendor

  coveralls:
    working_directory: /go/src/github.com/FactomProject/factom-walletd
    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-factom-walletd-go-build-cache-{{ checksum "glide.lock" }}

      - run:
          name: Get glide
          command: |
            go get -v github.com/Masterminds/glide
            cd $GOPATH/src/github.com/Masterminds/glide
            git checkout tags/v0.13.1
            go install

      - run:
          name: Get goveralls
          command: |
            go get github.com/mattn/goveralls
            cd $GOPATH/src/github.com/Masterminds/glide
            git checkout tags/v0.13.1
            go install

      - run:
          name: Get the dependencies
          command: |
            glide install

      - run:
          name: Build and install the executable
          command: go install -v

      - run:
          name: Coveralls!
          command: goveralls -v -flags "-vet=off" -ignore=$(paste -sd, .coverignore) -service=circle-ci -repotoken=$COVERALLS_TOKEN


      - save_cache:
          key: v1-factom-walletd-go-build-cache-{{ checksum "glide.lock" }}
          paths:
            - vendor

  # Build containers
  docker_build:
    working_directory: /go/src/github.com/FactomProject/factom-walletd

    docker:
      - image: factominc/elixir_python

    steps:
      - checkout

      - setup_remote_docker:
          version: 17.06.0-ce

      # The main (only) thing we care about is caching the /vendor dir.
      #   Hence, checksumming glide.lock
      - restore_cache:
          keys:
            - v2-factom-walletd-docker-cache-{{ checksum "glide.lock" }}

      # Load the image if the cache hit
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /images/factom-walletd-alpine.tar | true
            docker load -i /images/factom-walletd.tar | true

      # Build the containers
      - run:
          name: Build the baseline images
          command: |
            docker build -t factom-walletd-alpine -f Dockerfile.alpine .
            docker build -t factom-walletd -f Dockerfile .

      # Push, depending on branch/tag
      - run:
          name: Push  master / develop to DockerHub
          command: |

           # Login to DockerHub
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

            # If there is a tag, use it
            if [ "$CIRCLE_TAG" != "" ]; then
              docker tag factom-walletd factominc/factom-walletd:${CIRCLE_TAG}
              docker push factominc/factom-walletd:${CIRCLE_TAG}
              docker tag factom-walletd-alpine factominc/factom-walletd:${CIRCLE_TAG}-alpine
              docker push factominc/factom-walletd:${CIRCLE_TAG}-alpine
            fi

            if [ "${CIRCLE_BRANCH}" == "master" ]; then

              # Tag master as latest
              docker tag factom-walletd factominc/factom-walletd:latest
              docker push factominc/factom-walletd:latest
              docker tag factom-walletd-alpine factominc/factom-walletd:alpine
              docker push factominc/factom-walletd:alpine
            fi

            if [ "${CIRCLE_BRANCH}" == "develop" ]; then

              # Tag develop as develop anyhow
              docker tag factom-walletd factominc/factom-walletd:develop
              docker push factominc/factom-walletd:develop
              docker tag factom-walletd-alpine factominc/factom-walletd:alpine-develop
              docker push factominc/factom-walletd:alpine-develop
            fi

            docker logout

      - run:
          name: Push images to AWS ECR
          command: |
            # Login to AWS ECR
            login="$(aws ecr get-login  --no-include-email --region $AWS_REGION)"
            ${login}

            # If there is a tag, use it
            if [ "$CIRCLE_TAG" != "" ]; then
              docker tag factom-walletd ${AWS_REPO_BASE_URI}/factom-walletd:${CIRCLE_TAG}
              docker push ${AWS_REPO_BASE_URI}/factom-walletd:${CIRCLE_TAG}
              docker tag factom-walletd-alpine ${AWS_REPO_BASE_URI}/factom-walletd:${CIRCLE_TAG}-alpine
              docker push ${AWS_REPO_BASE_URI}/factom-walletd:${CIRCLE_TAG}-alpine
            fi

            if [ "${CIRCLE_BRANCH}" == "master" ]; then

              # Tag master as latest
              docker tag factom-walletd ${AWS_REPO_BASE_URI}/factom-walletd:latest
              docker push ${AWS_REPO_BASE_URI}/factom-walletd:latest
              docker tag factom-walletd-alpine ${AWS_REPO_BASE_URI}/factom-walletd:alpine
              docker push ${AWS_REPO_BASE_URI}/factom-walletd:alpine
            fi

            if [ "${CIRCLE_BRANCH}" == "develop" ]; then

              # Tag develop as develop anyhow
              docker tag factom-walletd ${AWS_REPO_BASE_URI}/factom-walletd:develop
              docker push ${AWS_REPO_BASE_URI}/factom-walletd:develop
              docker tag factom-walletd-alpine ${AWS_REPO_BASE_URI}/factom-walletd:alpine-develop
              docker push ${AWS_REPO_BASE_URI}/factom-walletd:alpine-develop
            fi


      - run:
          name: Save the image cache
          command: |
            mkdir -p /images
            docker save -o /images/factom-walletd-alpine.tar factom-walletd-alpine $(docker history -q factom-walletd-alpine |grep -v missing | grep -v none)
            docker save -o /images/factom-walletd.tar factom-walletd $(docker history -q factom-walletd |grep -v missing | grep -v none)

      - save_cache:
          key: v2-factom-walletd-docker-cache-{{ checksum "glide.lock" }}
          paths:
            - /images

# The flow is
#    build
#      |
#      ---------- test
#                   |
#                   ---------- coveralls
#                   |
#                   ---------- docker_build
#
#

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
          requires:
            - build
      - coveralls:
          filters:
            tags:
              only: /.*/
          requires:
            - test
      - docker_build:
          filters:
            tags:
              only: /.*/
          context: org-global
          requires:
            - test

  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only: develop
    jobs:
      - build
      - test:
          requires:
            - build
      - coveralls:
          requires:
            - test
      - docker_build:
          context: org-global
          requires:
            - test